### PR TITLE
Use lowercase imports to compile on Linux

### LINKED ISSUE #4: Compile error: core/Thread.d cannot be read
Can't compile on LinuxMint17.3RosaX86_64KDE4.14.2Qt4.8.6Plasma4.11.11

```shell
walkman@WalkmanLM17:/src > git clone https://github.com/deavmi/VioletDB
Cloning into 'VioletDB'...
remote: Counting objects: 170, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 170 (delta 19), reused 0 (delta 0), pack-reused 119
Receiving objects: 100% (170/170), 229.93 KiB | 100.00 KiB/s, done.
Resolving deltas: 100% (76/76), done.
walkman@WalkmanLM17:/src > cd VioletDB/
walkman@WalkmanLM17:/src/VioletDB > dmd violet.d database/* network/* misc/*
network/server.d(4): Error: module Thread is in file 'core/Thread.d' which cannot be read
import path[0] = /usr/include/dmd/phobos
import path[1] = /usr/include/dmd/druntime/import
walkman@WalkmanLM17:/src/VioletDB >
```

### PR DESCRIPTION
**Pull request by Walkman100**
Fixes #4

### CODE REVIEW

**Comment by deavmi** [comment]
Stupid windows filesystem created for normies

**Comment by deavmi** [comment]
Merged.
