### ISSUE TITLE
Compile error: core/Thread.d cannot be read

### ISSUE THREAD

**Issue by Walkman100** [deavmi/VioletDB#4]
Can't compile on LinuxMint17.3RosaX86_64KDE4.14.2Qt4.8.6Plasma4.11.11

```shell
walkman@WalkmanLM17:/src > git clone https://github.com/deavmi/VioletDB
Cloning into 'VioletDB'...
remote: Counting objects: 170, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 170 (delta 19), reused 0 (delta 0), pack-reused 119
Receiving objects: 100% (170/170), 229.93 KiB | 100.00 KiB/s, done.
Resolving deltas: 100% (76/76), done.
walkman@WalkmanLM17:/src > cd VioletDB/
walkman@WalkmanLM17:/src/VioletDB > dmd violet.d database/* network/* misc/*
network/server.d(4): Error: module Thread is in file 'core/Thread.d' which cannot be read
import path[0] = /usr/include/dmd/phobos
import path[1] = /usr/include/dmd/druntime/import
walkman@WalkmanLM17:/src/VioletDB >
```

**Comment by deavmi** [comment]
Idk of this will do anything but try with sudo?

Can the file, `Thread.d`, be opened with `nano`?

**Comment by Walkman100** [comment]
`sudo` has no effect, and I'm busy searching for a file called `Thread.d`

**Comment by deavmi** [comment]
Good.

**Comment by deavmi** [comment]
It sounds familiar this error to me.

**Comment by Walkman100** [comment]
k found it at `/usr/include/dmd/druntime/import/core/thread.d`. Will send a PR to use lowercase

**Comment by deavmi** [comment]
Thanks. Will accept and merge tomoz after review (but keep them coming).
